# Site settings
title: Caro chan
email: mikiai69@hotmail.com
url: https://github.com/Carochan
description: "The place where the magic happens"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #f9f2fe
  secondary: 2c3e50 #Fffefee
  secondary-dark: 233140 #767795

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: London
  social: Around the Web
  credits: Made with love &heart

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mikiai
  - title: facebook
    url:https://www.facebook.com/caro.pi.valenzuela
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: second star on the right
  - line: My own universe

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
